.common:
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - node --version
    - yarn --version
    - yarn

test:
  extends: .common
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - coverage/lcov.info

codecov:
  extends: .common
  stage: deploy
  only:
    - master@Bauke/fancify
  script:
    - yarn codecov
  dependencies:
    - test
