image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - node --version
  - yarn --version
  - yarn

test:
  environment:
    name: codecov
  only:
    - master
  script:
    - yarn test
    - npx codecov
