image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - node --version
  - yarn --version
  - yarn

test:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - coverage/lcov.info

codecov:
  stage: deploy
  environment:
    name: codecov
  only:
    - master@bauke/fancify
  script:
    - yarn codecov
  dependencies:
    - test
